folio-org/edge-orders

pom.xml
ramls/orders.xsd
src/main/java/org/folio/edge/orders/Constants.java
src/main/java/org/folio/edge/orders/OrdersHandler.java
src/main/java/org/folio/edge/orders/ValidateHandler.java
src/main/java/org/folio/edge/orders/model/ErrorWrapper.java
src/main/java/org/folio/edge/orders/utils/OrdersOkapiClient.java
src/test/java/org/folio/edge/orders/MainVerticleTest.java
src/test/java/org/folio/edge/orders/model/ErrorWrapperTest.java
src/test/java/org/folio/edge/orders/utils/OrdersMockOkapi.java
src/test/java/org/folio/edge/orders/utils/OrdersOkapiClientTest.java

* Refactor to remove duplicate code blocks identified by SonarQube 
* Leverage better error handling change in edge-common
* Handle XML or JSON responses from mod-gobi
* Use the new ApiKeyUtils from edge-common

Several minor enhancements

---

pom.xml
src/main/java/org/folio/edge/orders/Constants.java
src/main/java/org/folio/edge/orders/OrdersHandler.java
src/test/java/org/folio/edge/orders/MainVerticleTest.java

leverage the new invalidApiKey hook in edge-common's Handler class.

leverage new invalidApiKey hook

---

.editorconfig
.gitignore
NEWS.md
pom.xml
src/main/resources/ephemeral.properties

* Added missing `.editorconfig` and `.gitignore`
* Updated to released edge-common 1.0.0
* Added the maven-release-plugin required to do the release
* Updated maven plugin versions to the latest
* Updated the `ephemeral.properties` to conform to the edge-common 1.0.0 format

Prepare the repo for the release

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/EDGORDERS-14 Create the 2.0.0 Release
Update NEWS.md file
Upgrading the gobi dependency to 1.2, which the latest available version

EDGEORDERS-14 - Release  2.0.0 

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[EDGORDERS-17](https://issues.folio.org/browse/EDGORDERS-17) - edge-orders release 2.0.2

EDGORDERS-17 - Release 2.0.2

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Release edge-orders-2.1.0
Updated required gobi version

EDGORDERS-19 - Release 2.1.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[EDGORDERS-23](https://issues.folio.org/browse/EDGORDERS-23)
- news update
- update required interfaces: gobi:1.9
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?  
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

Tmp release 2.2.0

---

NEWS.md
pom.xml

Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com>

[EDGORDERS-32] EDGORDERS (edge-orders) release

---

pom.xml
ramls/edge-orders.raml
ramls/traits/errors.raml
src/main/java/org/folio/edge/orders/OrdersHandler.java
src/main/java/org/folio/edge/orders/utils/OrdersOkapiClient.java
src/main/resources/api_configuration.json
src/test/java/org/folio/edge/orders/MainVerticleTest.java
src/test/java/org/folio/edge/orders/model/ResponseWrapperTest.java
src/test/java/org/folio/edge/orders/utils/OrdersMockOkapi.java
src/test/java/org/folio/edge/orders/utils/OrdersOkapiClientTest.java

[EDGORDERS-40](https://issues.folio.org/browse/EDGORDERS-40)
Add routing definition to mod-ebsconet
- Add EBSCONET routing
- Add put request handler
- Add handling of path parameters via /:variableName
- Update edge-common module
- Update unit tests

EDGORDERS-40 Add routing definition to mod-ebsconet

---

src/main/java/org/folio/edge/orders/OrdersHandler.java

[EDGORDERS-34](https://issues.folio.org/browse/EDGORDERS-34)
- update logic to ignore case for type

[EDGORDERS-34] Type parameter needs to be case-insensitive

---

NEWS.md
pom.xml

EDGORDERS-42 release 2.4.0

---

pom.xml

https://issues.folio.org/browse/EDGORDERS-45

EDGORDERS-45. Kiwi R3 2021 - Log4j vulnerability verification and correction

---

pom.xml

https://issues.folio.org/browse/EDGORDERS-50

EDGORDERS-50. Kiwi R3 2021 - Log4j edge- modules 2.17.0 upgrade

---

NEWS.md
pom.xml

https://issues.folio.org/browse/EDGORDERS-51

EDGORDERS-51. Kiwi R3 2021 Log4j module release

---

NEWS.md
pom.xml

EDGORDERS-56 release 2.5.0 Lotus R1

---

pom.xml
src/main/java/org/folio/edge/orders/MainVerticle.java
src/main/java/org/folio/edge/orders/OrdersHandler.java
src/main/java/org/folio/edge/orders/utils/OrdersOkapiClient.java
src/main/java/org/folio/edge/orders/utils/OrdersOkapiClientFactory.java
src/test/java/org/folio/edge/orders/MainVerticleTest.java
src/test/java/org/folio/edge/orders/utils/OrdersMockOkapi.java
src/test/java/org/folio/edge/orders/utils/OrdersOkapiClientFactoryTest.java
src/test/java/org/folio/edge/orders/utils/OrdersOkapiClientTest.java

https://issues.folio.org/browse/EDGORDERS-57
* migrated vertx to the v4.3.1
* updated code according to vertx breaking changes

EDGORDERS-57 migrated vertx to the v4.3.1

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODEBSNET-39
Major version of mod-ebsconet increased, so need to increase it in this module, also increase minor version of gobi to the latest one

MODEBSNET-39. Increase versions for gobi and ebsconet contracts

---

NEWS.md
descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/EDGORDERS-62

[EDGORDERS-62] Release R2 2022 Morning Glory Bug Fix 1

---

src/main/java/org/folio/edge/orders/utils/OrdersOkapiClient.java
src/test/java/org/folio/edge/orders/utils/OrdersOkapiClientTest.java

https://issues.folio.org/browse/EDGORDERS-65
HTTP code 406 returned for PUT requests towards mod-ebsconet endpoint.
Extended `"Accept"` header with `"application/json"` value

EDGORDERS-65 extended Accept header

---

src/main/java/org/folio/edge/orders/MainVerticle.java
src/main/java/org/folio/edge/orders/OrdersHandler.java
src/main/java/org/folio/edge/orders/model/ErrorWrapper.java
src/main/java/org/folio/edge/orders/model/ResponseWrapper.java
src/main/java/org/folio/edge/orders/utils/OrdersOkapiClient.java
src/main/resources/log4j.properties
src/main/resources/log4j2-json.properties
src/main/resources/log4j2.properties

https://issues.folio.org/browse/EDGORDERS-55
Logging has been improved for more productive troubleshooting.

[EDGORDERS-55] - Logging Improvement

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[EDGORDERS-77](https://issues.folio.org/browse/EDGORDERS-77) - edge-orders: module release

[EDGORDERS-77] - Release v2.9.0

---

pom.xml

https://folio-org.atlassian.net/browse/EDGORDERS-80
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146

[EDGORDERS-80] Upgrade RAML Module Builder

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/EDGORDERS-81

[EDGORDERS-81] - Release v3.0.0

---

NEWS.md
pom.xml

Including vertx dependency update

Hot Fix Release v3.0.2

---

pom.xml

https://folio-org.atlassian.net/browse/EDGORDERS-89

EDGORDERS-89. Release fix for Q CSP #1 regarding encyption in transit

---

NEWS.md
pom.xml

Released this pr https://github.com/folio-org/edge-orders/pull/82/files related to ticket https://folio-org.atlassian.net/browse/EDGORDERS-89

Hot Fix Release v3.0.3

---

pom.xml

[[EDGORDERS-90] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/EDGORDERS-90)
- Update versions
- Add module descriptor validator

[EDGORDERS-90] Update libraries of dependant acq modules to the latest versions

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/FOLIO-4102

Release v3.1.0

---

README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/edge/orders/Constants.java
src/main/java/org/folio/edge/orders/MainVerticle.java
src/main/java/org/folio/edge/orders/OrdersHandler.java
src/main/java/org/folio/edge/orders/Param.java
src/main/java/org/folio/edge/orders/utils/OrdersOkapiClient.java
src/main/resources/api_configuration.json
src/test/java/org/folio/edge/orders/CommonEndpoint.java
src/test/java/org/folio/edge/orders/MainVerticleTest.java
src/test/java/org/folio/edge/orders/MosaicEndpoint.java
src/test/java/org/folio/edge/orders/model/ErrorWrapperTest.java
src/test/java/org/folio/edge/orders/model/ResponseWrapperTest.java
src/test/java/org/folio/edge/orders/utils/OrdersMockOkapi.java
src/test/java/org/folio/edge/orders/utils/OrdersOkapiClientTest.java

- <https://folio-org.atlassian.net/browse/EDGORDERS-96>
- Add new proxy methods of the type MOSAIC
- Add methods to set CQL-based query string params (i.e. `offset`, `limit` and `query`)
- Add setting of a new header `x-okapi-module-id` to satisfy the requirements of  `GET /custom-fields` endpoint

[EDGORDERS-96]. Build GET APIs for field data that is critical to order integrations

---

src/main/resources/api_configuration.json
src/test/java/org/folio/edge/orders/CommonEndpoint.java
src/test/java/org/folio/edge/orders/MainVerticleTest.java
src/test/java/org/folio/edge/orders/MosaicEndpoint.java

- <https://folio-org.atlassian.net/browse/EDGORDERS-96>
- Change MOSAIC and COMMON endpoints by removing /mosaic/ from MOSAIC and /locations from COMMON
- GET /locations already available in edge-inventory

[EDGORDERS-96-4]. Change MOSAIC and COMMON endpoints

---

README.md

- <https://folio-org.atlassian.net/browse/EDGORDERS-96>
- Add missing MOSAIC and COMMON permissions to README.md

[EDGORDERS-96-5]. Update README.md with MOSAIC & COMMON perms
